packages:
  - '.'
  - 'cli'
  - 'docs'

overrides:
  sharp: 0.34.5

packageExtensions:
  '@nuxt/scripts':
    dependencies:
      'estree-walker': '^3.0.3'

patchedDependencies:
  '@jsr/deno__doc@0.189.1': 'patches/@jsr__deno__doc@0.189.1.patch'

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver

onlyBuiltDependencies:
  - better-sqlite3@12.5.0
  - sharp@0.34.5
  - simple-git-hooks@2.13.1

ignoreWorkspaceRootCheck: true
