import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest'
import { buildCompareScatterChartDataset } from '~/utils/compare-scatter-chart'

vi.mock('~/utils/charts', () => ({
  applyEllipsis: vi.fn((value: string, limit: number) => `ellipsis(${value},${limit})`),
}))

vi.mock('~/utils/frameworks', () => ({
  isListedFramework: vi.fn((name: string) => name === 'vue'),
  getFrameworkColor: vi.fn((name: string) => `color:${name}`),
}))

describe('buildCompareScatterChartDataset', () => {
  beforeEach(() => {
    vi.useFakeTimers()
    vi.setSystemTime(new Date('2026-04-11T12:00:00.000Z'))
  })

  afterEach(() => {
    vi.useRealTimers()
    vi.clearAllMocks()
  })

  it('builds a dataset entry with raw values, full name, ellipsed name, and framework color', () => {
    const packagesData = [
      {
        package: { name: 'vue' },
        downloads: 1200,
        installSize: { totalSize: 4096 },
      },
    ] as PackageComparisonData[]

    const result = buildCompareScatterChartDataset(
      packagesData,
      ['fallback-package'],
      'downloads',
      'installSize',
    )

    expect(result).toEqual([
      {
        name: 'ellipsis(vue,14)',
        fullName: 'vue',
        color: 'color:vue',
        values: [
          {
            x: 1200,
            y: 4096,
            name: 'ellipsis(vue,14)',
            fullName: 'vue',
          },
        ],
      },
    ])
  })

  it('does not set a color when the package is not a listed framework', () => {
    const packagesData = [
      {
        package: { name: 'some-library' },
        downloads: 100,
        installSize: { totalSize: 200 },
      },
    ] as PackageComparisonData[]

    const result = buildCompareScatterChartDataset(
      packagesData,
      ['fallback-package'],
      'downloads',
      'installSize',
    )

    expect(result).toEqual([
      {
        name: 'ellipsis(some-library,14)',
        fullName: 'some-library',
        color: undefined,
        values: [
          {
            x: 100,
            y: 200,
            name: 'ellipsis(some-library,14)',
            fullName: 'some-library',
          },
        ],
      },
    ])
  })

  it('uses the fallback package name when package.name is missing', () => {
    const packagesData = [
      {
        downloads: 50,
        installSize: { totalSize: 75 },
      },
    ] as PackageComparisonData[]

    const result = buildCompareScatterChartDataset(
      packagesData,
      ['fallback-name'],
      'downloads',
      'installSize',
    )

    expect(result).toEqual([
      {
        name: 'ellipsis(fallback-name,14)',
        fullName: 'fallback-name',
        color: undefined,
        values: [
          {
            x: 50,
            y: 75,
            name: 'ellipsis(fallback-name,14)',
            fullName: 'fallback-name',
          },
        ],
      },
    ])
  })

  it('uses an autogenerated fallback package name when packages[index] is missing', () => {
    const packagesData = [
      {
        downloads: 10,
        installSize: { totalSize: 20 },
      },
    ] as PackageComparisonData[]

    const result = buildCompareScatterChartDataset(packagesData, [], 'downloads', 'installSize')

    expect(result).toEqual([
      {
        name: 'ellipsis(package-1,14)',
        fullName: 'package-1',
        color: undefined,
        values: [
          {
            x: 10,
            y: 20,
            name: 'ellipsis(package-1,14)',
            fullName: 'package-1',
          },
        ],
      },
    ])
  })

  it('preserves the package index when determining fallback names', () => {
    const packagesData = [
      null,
      {
        downloads: 11,
        installSize: { totalSize: 22 },
      },
    ] as ReadonlyArray<PackageComparisonData | null>

    const result = buildCompareScatterChartDataset(
      packagesData,
      ['unused-first'],
      'downloads',
      'installSize',
    )

    expect(result).toEqual([
      {
        name: 'ellipsis(package-2,14)',
        fullName: 'package-2',
        color: undefined,
        values: [
          {
            x: 11,
            y: 22,
            name: 'ellipsis(package-2,14)',
            fullName: 'package-2',
          },
        ],
      },
    ])
  })

  it('uses the fallback name when package.name is an empty string', () => {
    const packagesData = [
      {
        package: { name: '' },
        downloads: 12,
        installSize: { totalSize: 34 },
      },
    ] as unknown as PackageComparisonData[]

    const result = buildCompareScatterChartDataset(
      packagesData,
      ['fallback-empty-name'],
      'downloads',
      'installSize',
    )

    expect(result).toEqual([
      {
        name: 'ellipsis(fallback-empty-name,14)',
        fullName: 'fallback-empty-name',
        color: undefined,
        values: [
          {
            x: 12,
            y: 34,
            name: 'ellipsis(fallback-empty-name,14)',
            fullName: 'fallback-empty-name',
          },
        ],
      },
    ])
  })

  it('skips null package entries', () => {
    const packagesData = [
      null,
      {
        package: { name: 'vue' },
        downloads: 200,
        installSize: { totalSize: 300 },
      },
    ] as ReadonlyArray<PackageComparisonData | null>

    const result = buildCompareScatterChartDataset(
      packagesData,
      ['first', 'second'],
      'downloads',
      'installSize',
    )

    expect(result).toEqual([
      {
        name: 'ellipsis(vue,14)',
        fullName: 'vue',
        color: 'color:vue',
        values: [
          {
            x: 200,
            y: 300,
            name: 'ellipsis(vue,14)',
            fullName: 'vue',
          },
        ],
      },
    ])
  })

  it('skips entries when the x facet resolves to null', () => {
    const packagesData = [
      {
        package: { name: 'pkg-a' },
        downloads: 'invalid',
        installSize: { totalSize: 300 },
      },
    ] as unknown as PackageComparisonData[]

    const result = buildCompareScatterChartDataset(
      packagesData,
      ['pkg-a'],
      'downloads',
      'installSize',
    )

    expect(result).toEqual([])
  })

  it('skips entries when the y facet resolves to null', () => {
    const packagesData = [
      {
        package: { name: 'pkg-a' },
        downloads: 300,
        installSize: { totalSize: undefined },
      },
    ] as unknown as PackageComparisonData[]

    const result = buildCompareScatterChartDataset(
      packagesData,
      ['pkg-a'],
      'downloads',
      'installSize',
    )

    expect(result).toEqual([])
  })

  it('skips entries when a numeric facet is Infinity', () => {
    const packagesData = [
      {
        package: { name: 'infinite-downloads-package' },
        downloads: Infinity,
        installSize: { totalSize: 200 },
      },
    ] as unknown as PackageComparisonData[]

    const result = buildCompareScatterChartDataset(
      packagesData,
      ['infinite-downloads-package'],
      'downloads',
      'installSize',
    )

    expect(result).toEqual([])
  })

  it('maps the types facet to 1 when a type kind exists and to 0 otherwise', () => {
    const packagesData = [
      {
        package: { name: 'typed-package' },
        analysis: { types: { kind: 'included' } },
        downloads: 120,
      },
      {
        package: { name: 'untyped-package' },
        analysis: { types: { kind: '' } },
        downloads: 140,
      },
    ] as PackageComparisonData[]

    const result = buildCompareScatterChartDataset(
      packagesData,
      ['typed-package', 'untyped-package'],
      'types',
      'downloads',
    )

    expect(result).toEqual([
      {
        name: 'ellipsis(typed-package,14)',
        fullName: 'typed-package',
        color: undefined,
        values: [
          {
            x: 1,
            y: 120,
            name: 'ellipsis(typed-package,14)',
            fullName: 'typed-package',
          },
        ],
      },
      {
        name: 'ellipsis(untyped-package,14)',
        fullName: 'untyped-package',
        color: undefined,
        values: [
          {
            x: 0,
            y: 140,
            name: 'ellipsis(untyped-package,14)',
            fullName: 'untyped-package',
          },
        ],
      },
    ])
  })

  it('returns 0 for the types facet when analysis.types is missing', () => {
    const packagesData = [
      {
        package: { name: 'pkg-no-types' },
        downloads: 77,
        analysis: {},
      },
    ] as unknown as PackageComparisonData[]

    const result = buildCompareScatterChartDataset(
      packagesData,
      ['pkg-no-types'],
      'types',
      'downloads',
    )

    expect(result).toEqual([
      {
        name: 'ellipsis(pkg-no-types,14)',
        fullName: 'pkg-no-types',
        color: undefined,
        values: [
          {
            x: 0,
            y: 77,
            name: 'ellipsis(pkg-no-types,14)',
            fullName: 'pkg-no-types',
          },
        ],
      },
    ])
  })

  it('maps nested numeric facets correctly', () => {
    const packagesData = [
      {
        package: { name: 'pkg-nested' },
        directDeps: 12,
        installSize: {
          dependencyCount: 34,
          totalSize: 1024,
        },
        vulnerabilities: {
          count: 2,
        },
      },
    ] as PackageComparisonData[]

    expect(
      buildCompareScatterChartDataset(
        packagesData,
        ['pkg-nested'],
        'dependencies',
        'totalDependencies',
      ),
    ).toEqual([
      {
        name: 'ellipsis(pkg-nested,14)',
        fullName: 'pkg-nested',
        color: undefined,
        values: [
          {
            x: 12,
            y: 34,
            name: 'ellipsis(pkg-nested,14)',
            fullName: 'pkg-nested',
          },
        ],
      },
    ])

    expect(
      buildCompareScatterChartDataset(
        packagesData,
        ['pkg-nested'],
        'vulnerabilities',
        'packageSize',
      ),
    ).toEqual([])
  })

  it('maps totalLikes and packageSize facets correctly', () => {
    const packagesData = [
      {
        package: { name: 'metrics-package' },
        totalLikes: 42,
        packageSize: 2048,
      },
    ] as PackageComparisonData[]

    const result = buildCompareScatterChartDataset(
      packagesData,
      ['metrics-package'],
      'totalLikes',
      'packageSize',
    )

    expect(result).toEqual([
      {
        name: 'ellipsis(metrics-package,14)',
        fullName: 'metrics-package',
        color: undefined,
        values: [
          {
            x: 42,
            y: 2048,
            name: 'ellipsis(metrics-package,14)',
            fullName: 'metrics-package',
          },
        ],
      },
    ])
  })

  it('maps vulnerabilities and packageSize facets correctly when both are present', () => {
    const packagesData = [
      {
        package: { name: 'security-package' },
        packageSize: 512,
        vulnerabilities: {
          count: 3,
        },
      },
    ] as PackageComparisonData[]

    const result = buildCompareScatterChartDataset(
      packagesData,
      ['security-package'],
      'vulnerabilities',
      'packageSize',
    )

    expect(result).toEqual([
      {
        name: 'ellipsis(security-package,14)',
        fullName: 'security-package',
        color: undefined,
        values: [
          {
            x: 3,
            y: 512,
            name: 'ellipsis(security-package,14)',
            fullName: 'security-package',
          },
        ],
      },
    ])
  })

  it('returns 100 freshness for a package updated just now', () => {
    const now = new Date('2026-04-11T12:00:00.000Z')

    const packagesData = [
      {
        package: { name: 'fresh-package' },
        metadata: { lastUpdated: now.toISOString() },
        downloads: 1000,
      },
    ] as PackageComparisonData[]

    const result = buildCompareScatterChartDataset(
      packagesData,
      ['fresh-package'],
      'lastUpdated',
      'downloads',
    )

    expect(result).toEqual([
      {
        name: 'ellipsis(fresh-package,14)',
        fullName: 'fresh-package',
        color: undefined,
        values: [
          {
            x: 100,
            y: 1000,
            name: 'ellipsis(fresh-package,14)',
            fullName: 'fresh-package',
          },
        ],
      },
    ])
  })

  it('returns 0 freshness for a package older than the maximum age window', () => {
    const olderThanOneYear = new Date('2025-04-10T12:00:00.000Z')

    const packagesData = [
      {
        package: { name: 'stale-package' },
        metadata: { lastUpdated: olderThanOneYear.toISOString() },
        downloads: 1000,
      },
    ] as PackageComparisonData[]

    const result = buildCompareScatterChartDataset(
      packagesData,
      ['stale-package'],
      'lastUpdated',
      'downloads',
    )

    expect(result).toEqual([
      {
        name: 'ellipsis(stale-package,14)',
        fullName: 'stale-package',
        color: undefined,
        values: [
          {
            x: 0,
            y: 1000,
            name: 'ellipsis(stale-package,14)',
            fullName: 'stale-package',
          },
        ],
      },
    ])
  })

  it('returns a proportional freshness score for partially old dates', () => {
    const aboutHalfFresh = new Date('2025-10-11T12:00:00.000Z')

    const packagesData = [
      {
        package: { name: 'mid-package' },
        metadata: { lastUpdated: aboutHalfFresh.toISOString() },
        downloads: 321,
      },
    ] as PackageComparisonData[]

    const result = buildCompareScatterChartDataset(
      packagesData,
      ['mid-package'],
      'lastUpdated',
      'downloads',
    )

    expect(result).toHaveLength(1)
    expect(result[0]?.values[0]?.x).toBeCloseTo(50.136986301369866)
    expect(result[0]?.values[0]?.y).toBe(321)
  })

  it('skips entries when lastUpdated is invalid', () => {
    const packagesData = [
      {
        package: { name: 'broken-date-package' },
        metadata: { lastUpdated: 'not-a-date' },
        downloads: 100,
      },
    ] as unknown as PackageComparisonData[]

    const result = buildCompareScatterChartDataset(
      packagesData,
      ['broken-date-package'],
      'lastUpdated',
      'downloads',
    )

    expect(result).toEqual([])
  })

  it('skips entries when lastUpdated is missing', () => {
    const packagesData = [
      {
        package: { name: 'missing-date-package' },
        metadata: {},
        downloads: 100,
      },
    ] as unknown as PackageComparisonData[]

    const result = buildCompareScatterChartDataset(
      packagesData,
      ['missing-date-package'],
      'lastUpdated',
      'downloads',
    )

    expect(result).toEqual([])
  })

  it('clamps freshness to 100 for future dates', () => {
    const futureDate = new Date('2026-04-12T12:00:00.000Z')

    const packagesData = [
      {
        package: { name: 'future-package' },
        metadata: { lastUpdated: futureDate.toISOString() },
        downloads: 100,
      },
    ] as PackageComparisonData[]

    const result = buildCompareScatterChartDataset(
      packagesData,
      ['future-package'],
      'lastUpdated',
      'downloads',
    )

    expect(result).toEqual([
      {
        name: 'ellipsis(future-package,14)',
        fullName: 'future-package',
        color: undefined,
        values: [
          {
            x: 100,
            y: 100,
            name: 'ellipsis(future-package,14)',
            fullName: 'future-package',
          },
        ],
      },
    ])
  })

  it('skips entries when an unsupported facet is provided', () => {
    const packagesData = [
      {
        package: { name: 'unknown-facet-package' },
        downloads: 10,
        installSize: { totalSize: 20 },
      },
    ] as PackageComparisonData[]

    const result = buildCompareScatterChartDataset(
      packagesData,
      ['unknown-facet-package'],
      'unknownFacet' as ComparisonFacet,
      'installSize',
    )

    expect(result).toEqual([])
  })

  it('skips entries when installSize is missing', () => {
    const packagesData = [
      {
        package: { name: 'missing-install-size-package' },
        downloads: 100,
      },
    ] as unknown as PackageComparisonData[]

    const result = buildCompareScatterChartDataset(
      packagesData,
      ['missing-install-size-package'],
      'downloads',
      'installSize',
    )

    expect(result).toEqual([])
  })

  it('supports Date instances for lastUpdated', () => {
    const packagesData = [
      {
        package: { name: 'date-instance-package' },
        metadata: { lastUpdated: new Date('2026-04-11T12:00:00.000Z') },
        downloads: 250,
      },
    ] as unknown as PackageComparisonData[]

    const result = buildCompareScatterChartDataset(
      packagesData,
      ['date-instance-package'],
      'lastUpdated',
      'downloads',
    )

    expect(result).toEqual([
      {
        name: 'ellipsis(date-instance-package,14)',
        fullName: 'date-instance-package',
        color: undefined,
        values: [
          {
            x: 100,
            y: 250,
            name: 'ellipsis(date-instance-package,14)',
            fullName: 'date-instance-package',
          },
        ],
      },
    ])
  })

  it('returns 0 for types when analysis is missing entirely', () => {
    const packagesData = [
      {
        package: { name: 'missing-analysis-package' },
        downloads: 88,
      },
    ] as unknown as PackageComparisonData[]

    const result = buildCompareScatterChartDataset(
      packagesData,
      ['missing-analysis-package'],
      'types',
      'downloads',
    )

    expect(result).toEqual([
      {
        name: 'ellipsis(missing-analysis-package,14)',
        fullName: 'missing-analysis-package',
        color: undefined,
        values: [
          {
            x: 0,
            y: 88,
            name: 'ellipsis(missing-analysis-package,14)',
            fullName: 'missing-analysis-package',
          },
        ],
      },
    ])
  })

  it('skips entries when totalDependencies is missing', () => {
    const packagesData = [
      {
        package: { name: 'missing-total-dependencies-package' },
        downloads: 100,
        installSize: {
          totalSize: 400,
        },
      },
    ] as unknown as PackageComparisonData[]

    const result = buildCompareScatterChartDataset(
      packagesData,
      ['missing-total-dependencies-package'],
      'downloads',
      'totalDependencies',
    )

    expect(result).toEqual([])
  })

  it('skips entries when vulnerabilities count is missing', () => {
    const packagesData = [
      {
        package: { name: 'missing-vulnerabilities-package' },
        packageSize: 512,
        vulnerabilities: {},
      },
    ] as unknown as PackageComparisonData[]

    const result = buildCompareScatterChartDataset(
      packagesData,
      ['missing-vulnerabilities-package'],
      'vulnerabilities',
      'packageSize',
    )

    expect(result).toEqual([])
  })

  it('returns 0 for types when kind is undefined', () => {
    const packagesData = [
      {
        package: { name: 'undefined-kind-package' },
        downloads: 91,
        analysis: {
          types: {},
        },
      },
    ] as unknown as PackageComparisonData[]

    const result = buildCompareScatterChartDataset(
      packagesData,
      ['undefined-kind-package'],
      'types',
      'downloads',
    )

    expect(result).toEqual([
      {
        name: 'ellipsis(undefined-kind-package,14)',
        fullName: 'undefined-kind-package',
        color: undefined,
        values: [
          {
            x: 0,
            y: 91,
            name: 'ellipsis(undefined-kind-package,14)',
            fullName: 'undefined-kind-package',
          },
        ],
      },
    ])
  })

  it('skips entries when totalDependencies is Infinity', () => {
    const packagesData = [
      {
        package: { name: 'infinite-total-dependencies-package' },
        downloads: 100,
        installSize: {
          dependencyCount: Infinity,
        },
      },
    ] as unknown as PackageComparisonData[]

    const result = buildCompareScatterChartDataset(
      packagesData,
      ['infinite-total-dependencies-package'],
      'downloads',
      'totalDependencies',
    )

    expect(result).toEqual([])
  })

  it('skips entries when vulnerabilities count is Infinity', () => {
    const packagesData = [
      {
        package: { name: 'infinite-vulnerabilities-package' },
        packageSize: 512,
        vulnerabilities: {
          count: Infinity,
        },
      },
    ] as unknown as PackageComparisonData[]

    const result = buildCompareScatterChartDataset(
      packagesData,
      ['infinite-vulnerabilities-package'],
      'vulnerabilities',
      'packageSize',
    )

    expect(result).toEqual([])
  })

  it('skips entries when installSize is undefined for totalDependencies', () => {
    const packagesData = [
      {
        package: { name: 'undefined-install-size-package' },
        downloads: 100,
      },
    ] as unknown as PackageComparisonData[]

    const result = buildCompareScatterChartDataset(
      packagesData,
      ['undefined-install-size-package'],
      'downloads',
      'totalDependencies',
    )

    expect(result).toEqual([])
  })

  it('skips entries when vulnerabilities is undefined', () => {
    const packagesData = [
      {
        package: { name: 'undefined-vulnerabilities-package' },
        packageSize: 512,
      },
    ] as unknown as PackageComparisonData[]

    const result = buildCompareScatterChartDataset(
      packagesData,
      ['undefined-vulnerabilities-package'],
      'vulnerabilities',
      'packageSize',
    )

    expect(result).toEqual([])
  })

  it('skips entries when totalLikes is missing', () => {
    const packagesData = [
      {
        package: { name: 'missing-total-likes-package' },
        packageSize: 100,
      },
    ] as unknown as PackageComparisonData[]

    const result = buildCompareScatterChartDataset(
      packagesData,
      ['missing-total-likes-package'],
      'totalLikes',
      'packageSize',
    )

    expect(result).toEqual([])
  })

  it('skips entries when totalLikes is Infinity', () => {
    const packagesData = [
      {
        package: { name: 'infinite-total-likes-package' },
        totalLikes: Infinity,
        packageSize: 100,
      },
    ] as unknown as PackageComparisonData[]

    const result = buildCompareScatterChartDataset(
      packagesData,
      ['infinite-total-likes-package'],
      'totalLikes',
      'packageSize',
    )

    expect(result).toEqual([])
  })

  it('skips entries when packageSize is missing', () => {
    const packagesData = [
      {
        package: { name: 'missing-package-size-package' },
        totalLikes: 42,
      },
    ] as unknown as PackageComparisonData[]

    const result = buildCompareScatterChartDataset(
      packagesData,
      ['missing-package-size-package'],
      'totalLikes',
      'packageSize',
    )

    expect(result).toEqual([])
  })

  it('skips entries when packageSize is Infinity', () => {
    const packagesData = [
      {
        package: { name: 'infinite-package-size-package' },
        totalLikes: 42,
        packageSize: Infinity,
      },
    ] as unknown as PackageComparisonData[]

    const result = buildCompareScatterChartDataset(
      packagesData,
      ['infinite-package-size-package'],
      'totalLikes',
      'packageSize',
    )

    expect(result).toEqual([])
  })

  it('skips entries when installSize totalSize is Infinity', () => {
    const packagesData = [
      {
        package: { name: 'infinite-install-size-package' },
        downloads: 100,
        installSize: {
          totalSize: Infinity,
        },
      },
    ] as unknown as PackageComparisonData[]

    const result = buildCompareScatterChartDataset(
      packagesData,
      ['infinite-install-size-package'],
      'downloads',
      'installSize',
    )

    expect(result).toEqual([])
  })

  it('skips entries when directDeps is missing', () => {
    const packagesData = [
      {
        package: { name: 'missing-direct-deps-package' },
        downloads: 100,
      },
    ] as unknown as PackageComparisonData[]

    const result = buildCompareScatterChartDataset(
      packagesData,
      ['missing-direct-deps-package'],
      'dependencies',
      'downloads',
    )

    expect(result).toEqual([])
  })

  it('skips entries when directDeps is Infinity', () => {
    const packagesData = [
      {
        package: { name: 'infinite-direct-deps-package' },
        directDeps: Infinity,
        downloads: 100,
      },
    ] as unknown as PackageComparisonData[]

    const result = buildCompareScatterChartDataset(
      packagesData,
      ['infinite-direct-deps-package'],
      'dependencies',
      'downloads',
    )

    expect(result).toEqual([])
  })
})
